command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/cal500_seal_static_spen_e7s9ldfl/config.json
  - --include-package=seal
  - --wandb_tags=dataset@cal500,model@seal,reference@e7s9ldfl
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: cal500_seal_static_spen_e7s9ldfl

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
