command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/bibtex_strat_dvn_9kdrnq9r.json
  - --include-package=seal
  - --wandb_tags=dataset@bibtex_strat,model@dvn,reference@9kdrnq9r
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: bibtex_strat_dvn_9kdrnq9r

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
