command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/genbase_ranking_ijad26g8.json
  - --include-package=seal
  - --wandb_tags=dataset@genbase,model@ranking,reference@ijad26g8
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: genbase_ranking_ijad26g8

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
