command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/seal_static_reference/expr_fun_SEAL-static-DVN_e7a7je0r/config.json
  - --include-package=seal
  - --wandb_tags=type@random_seeds,dataset@expr_fun,model@SEAL-static-DVN,reference@e7a7je0r
  - ${args}

method: grid

metric:
  goal: maximize
  name: validation/best_fixed_f1

name: expr_fun_SEAL-static-DVN_e7a7je0r

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334

program: allennlp
