command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/eurlexev_pnce_xk4u9lhz/config.json
  - --include-package=seal
  - --wandb_tags=dataset@eurlexev,model@pnce,reference@xk4u9lhz
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: eurlexev_pnce_xk4u9lhz

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
