command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/seal_static_reference/expr_fun_SEAL-static-NCE_zh26k4z7/config.json
  - --include-package=seal
  - --wandb_tags=type@random_seeds,dataset@expr_fun,model@SEAL-static-NCE,reference@zh26k4z7
  - ${args}

method: grid

metric:
  goal: maximize
  name: validation/best_fixed_f1

name: expr_fun_SEAL-static-NCE_zh26k4z7

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334

program: allennlp
