command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/seal_static_reference/genbase_SEAL-static-DVN_nk1osgte/config.json
  - --include-package=seal
  - --wandb_tags=type@random_seeds,dataset@genbase,model@SEAL-static-DVN,reference@nk1osgte
  - ${args}

method: grid

metric:
  goal: maximize
  name: validation/best_fixed_f1

name: genbase_SEAL-static-DVN_nk1osgte

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334

program: allennlp
