command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/eurlexev_spen_d2iw92pp.json
  - --include-package=seal
  - --wandb_tags=dataset@eurlexev,model@spen,reference@d2iw92pp
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: eurlexev_spen_d2iw92pp

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
