command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/cal500_ranking_ma82nwum.json
  - --include-package=seal
  - --wandb_tags=dataset@cal500,model@ranking,reference@ma82nwum
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: cal500_ranking_ma82nwum

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
