command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/seal_static_reference/eurlexev_SEAL-static-NCE_ny42kjkg/config.json
  - --include-package=seal
  - --wandb_tags=type@random_seeds,dataset@eurlexev,model@SEAL-static-NCE,reference@ny42kjkg
  - ${args}

method: grid

metric:
  goal: maximize
  name: validation/best_fixed_f1

name: eurlexev_SEAL-static-NCE_ny42kjkg

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334

program: allennlp
