command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/expr_fun_pnce_7y5cxq7w/config.json
  - --include-package=seal
  - --wandb_tags=dataset@expr_fun,model@pnce,reference@7y5cxq7w
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: expr_fun_pnce_7y5cxq7w

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
