command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/seal_static_reference/spo_fun_SEAL-static-DVN_9up68umh/config.json
  - --include-package=seal
  - --wandb_tags=type@random_seeds,dataset@spo_fun,model@SEAL-static-DVN,reference@9up68umh
  - ${args}

method: grid

metric:
  goal: maximize
  name: validation/best_fixed_f1

name: spo_fun_SEAL-static-DVN_9up68umh

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334

program: allennlp
