command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/spo_fun_pnce_vbhvkg77/config.json
  - --include-package=seal
  - --wandb_tags=dataset@spo_fun,model@pnce,reference@vbhvkg77
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: spo_fun_pnce_vbhvkg77

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
