command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/eurlexev_dvn_bg1hgggb.json
  - --include-package=seal
  - --wandb_tags=dataset@eurlexev,model@dvn,reference@bg1hgggb
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: eurlexev_dvn_bg1hgggb

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
