command:
  - ${program}
  - train_with_wandb
  - /mnt/nfs/work1/mccallum/scorenn/best_models_configs/delicious_dvn-samples_sx0h4gus.json
  - --include-package=seal
  - --wandb_tags=dataset@delicious,model@dvn-samples,reference@sx0h4gus
  - ${args}

method: grid
metric:
  goal: maximize
  name: validation/best_fixed_f1

name: delicious_dvn-samples_sx0h4gus

parameters:
  pytorch_seed:
    values:
      - 2
      - 123
      - 234
      - 579
      - 9099
      - 83
      - 444
      - 345
      - 735
      - 334
program: allennlp
