# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main, dev/main ]
    paths-ignore: ['docs/**'] # don't run when only docs are changed
  pull_request:
    branches: [ main, dev/main ]
    paths-ignore: ['docs/**']

jobs:
  tests:
    name: ${{ matrix.session }}-${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8']
        os: ['macos-latest', 'ubuntu-latest']
      fail-fast: true
    env:
      NOXSESSION: ${{ matrix.session }}

    steps:

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/checkout@v2
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install nox
      run: |
        pip install nox

    - name: Download data
      run: |
        sh download_data.sh

    - name: Run tests
      run: |
        nox --session=tests -- -x -v
